export const structuredQuoteResultJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "quote_type",
    "status",
    "customer",
    "vehicle",
    "coverage",
    "pricing",
    "underwriting",
    "warnings",
    "missing_information",
    "employee_notes",
    "customer_quote_text",
  ],
  properties: {
    quote_type: {
      type: "string",
      enum: ["AUTO_INSURANCE", "MODIFIED_VEHICLE_PROTECTION"],
    },
    status: {
      type: "string",
      enum: ["estimate", "needs_review", "missing_information", "error"],
    },
    customer: {
      type: "object",
      additionalProperties: false,
      required: ["name", "zip", "age", "dob", "gender"],
      properties: {
        name: { type: "string" },
        zip: { type: "string" },
        age: { type: "string" },
        dob: { type: "string" },
        gender: { type: "string" },
      },
    },
    vehicle: {
      type: "object",
      additionalProperties: false,
      required: ["year", "make", "model", "trim", "summary"],
      properties: {
        year: { type: "string" },
        make: { type: "string" },
        model: { type: "string" },
        trim: { type: "string" },
        summary: { type: "string" },
      },
    },
    coverage: {
      type: "object",
      additionalProperties: false,
      required: [
        "type",
        "tier",
        "deductible",
        "included_items",
        "excluded_or_not_included",
      ],
      properties: {
        type: { type: "string" },
        tier: { type: "string" },
        deductible: { type: "string" },
        included_items: { type: "array", items: { type: "string" } },
        excluded_or_not_included: {
          type: "array",
          items: { type: "string" },
        },
      },
    },
    pricing: {
      type: "object",
      additionalProperties: false,
      required: [
        "pricing_available",
        "monthly_estimate",
        "monthly_range",
        "six_month_estimate",
        "annual_estimate",
        "pricing_notes",
      ],
      properties: {
        pricing_available: { type: "boolean" },
        monthly_estimate: { type: "string" },
        monthly_range: { type: "string" },
        six_month_estimate: { type: "string" },
        annual_estimate: { type: "string" },
        pricing_notes: { type: "array", items: { type: "string" } },
      },
    },
    underwriting: {
      type: "object",
      additionalProperties: false,
      required: [
        "decision",
        "risk_score",
        "required_before_binding",
        "review_flags",
      ],
      properties: {
        decision: { type: "string" },
        risk_score: { type: "string" },
        required_before_binding: {
          type: "array",
          items: { type: "string" },
        },
        review_flags: { type: "array", items: { type: "string" } },
      },
    },
    warnings: { type: "array", items: { type: "string" } },
    missing_information: { type: "array", items: { type: "string" } },
    employee_notes: { type: "string" },
    customer_quote_text: { type: "string" },
  },
} as const;
